#!/bin/bash
# This complex program uses nested loops to
# read all lines of data in from a file,
# summing and averaging the contents of 
# each line.

lineNum=0
rows=0
cols=0

while read myLine
do 
	sum=0
	count=0
	average=0

	lineNum=$(( lineNum + 1 ))
	echo "Processing line $lineNum: $myLine"

	for i in $myLine
	do
		num=$i				#Also work with char
		count=$(( count + 1 ))		#Update count
		echo "Item $count: $num"	#Display count and number
		sum=$(( sum + num ))		#Update sum 
	done

	average=$(( sum / count ))		#Calculate average
	rows=$lineNum
	cols=$count


	echo "Line count: $count"		#Display count
	echo "Line sum: $sum"			#Display sum 
	echo "Line average: $average"		#Display average
done < $1						#stdin from arg1 (or piping stdout file)


echo "Rows: $rows"		#Display rows 
echo "Cols: $cols"		#Display cols
