#!/bin/bash
# Script demonstrates changing a row into a column 
# and back again using temp files

inputFile="tempinputfile"
tempRow="temprowfile"
tempCol="tempcolfile"

# Make the input row file
echo -e "1\t2\t3\t4\t5" > $inputFile

# Append each number onto the end of a temp col file
# by cutting specific columns
cut -c 1 $inputFile > $tempCol
cut -c 3 $inputFile >> $tempCol
cut -c 5 $inputFile >> $tempCol
cut -c 7 $inputFile >> $tempCol
cut -c 9 $inputFile >> $tempCol

# Convert the col file back into a row file
cat $tempCol | tr '\n' '\t' > "$tempRow$$"

# Add a newline character to the end of the row
# for easier reading
echo -e "" >> "$tempRow$$"
