#!/bin/bash
# Name: Travis Laxson
# Date: Jan. 18 2019
# Description: This shell script computes matrix operations 
# including printing the dimensions, matrix transpositions,
# mean vector calculation, addition of two matrices, and
# multiplication of two matrices. 

datafilepath="datafile$$"
trap "rm -f $datafilepath" EXIT INT HUP TERM 	# Remove data file after dims function executes 

#if [ "$#" = "0" ]
#then
#	cat > "$datafilepath"		
#elif [ "$#" = "1" ]
#then
#	datafilepath=$1
#fi


# Dims function: Prints the dimensions of the matrix
# as the number of rows, followed by a space, then the number
# of columns (e.g. For a 5x6 matrix stdout will show '5 6')
dims() {	
	rows=0
	while read numberLine 
	do
		rows=$(( rows + 1 ))		# Update row count
		cols=0				# Initialize columns 	
		for i in $numberLine	# Iterate over each value per row
		do
			cols=$(( cols + 1 ))	# Update column count
		done
	done < $datafilepath			# Stdin from arg1 (or piping stdout file)
	echo "$rows $cols"			# Display rows and cols
}

if [ "$#" = "1" ]
then
	cat > $datafilepath			#read in stdin to data file
elif [ "$#" = "2" ]
then
	datafilepath=$2				
fi


transpose() {
	tempCol="tmpcolfile$$"
#	tempRow="tmprowfile$$"
	i=0
	#Make input row file
	while read numberLine
	do
	#	echo "Line numbers: $numberLine"
		#i=1
	#	lincount=$(wc -l < $datafilepath)
	#	wordcount=$(wc -w < $datafilepath)
	#	newcount=$(( wordcount / lincount ))
	#	echo "lines in file = $lincount"
	#	echo "words in file = $wordcount"
		#for i in $numberLine
		#i=0
		colscount=0
		for each in $numberLine 
		do			
			colscount=$(( colscount + 1 ))
		done
		#echo "Column count: $colscount"
		
		while [[ $i -lt $colscount ]]
		do
			(( i++ ))	
#			echo "i = $i"
			col=$(cut -f $i $datafilepath | tr '\n' '\t')
			#echo "hello : $col"
			echo "${col%?}" >> $tempCol
			#(( i++ ))
			#echo "$col"
		done

		#cat < $tempCol

	#Append each number onto the end of a temp col file by cutting specific cols
	#cut -c 1 $inputFile > $tempCol
	#cut -c 3 $inputFile >> $tempCol
	#cut -c 5 $inputFile >> $tempCol
	#cut -c 7 $inputFile >> $tempCol
	#cut -c 9 $inputFile >> $tempCol
	#echo "Status code: $?"

#	cat $tempCol | tr '\n' '\t' >> "$tempRow$$"

#	echo >> "$tempRow$$"

	done < $datafilepath

	
	cat < $tempCol
}


	

# If number of args is greater than 2 or the file doesn't exist
# print error message to stderr, nothing to stdout and return 1
# else print the number of rows and cols to stdout and return 0
if [ $# -gt 2 ] || [ $# -lt 1 ] 
then
	echo "Error: Improper argument count" 1>&2
	exit 1
fi

if [ ! -f $datafilepath ]
then
	echo "Error: File $datafilepath does not exist." 1>&2
	exit 1
fi

#if [ $# -eq 1 ] || [ $# -eq 2 ]
#then
#	dims $datafilepath	
#	exit 0
#fi

$1 "${@:2}"


